[Interface]
# TODO
PrivateKey = <>
###
ListenPort = 51820
Address = 10.10.11.10/24
SaveConfig = true
#
PostUp = ufw route allow in on %i out on eth0
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
##
PostUp = iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-ports 8080
PostUp = iptables -t nat -A PREROUTING -p tcp --destination-port 443 -j REDIRECT --to-ports 8080
#
PreDown = ufw route delete allow in on %i out on eth0
PreDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
##
PreDown = iptables -t nat -D PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-ports 8080
PreDown = iptables -t nat -D PREROUTING -p tcp --destination-port 443 -j REDIRECT --to-ports 8080

[Peer]
# TODO
PublicKey = <>
###
AllowedIPs = 10.10.11.0/24
